/**
 * Stable error codes shared across services.
 *
 * Using a constant instead of a string literal avoids typos and lets the
 * frontend branch on a well-typed value.
 */
export const ERROR_CODES = {
  // Auth (AUTH_*)
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',

  // Users (USER_*)
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_DISABLED: 'USER_DISABLED',
  USER_DATA_CLEARED: 'USER_DATA_CLEARED',
  USER_MAX_EXCEEDED: 'USER_MAX_EXCEEDED',

  // Graph (GRAPH_*)
  GRAPH_ONTOLOGY_NOT_FOUND: 'GRAPH_ONTOLOGY_NOT_FOUND',
  GRAPH_ENTITY_NOT_FOUND: 'GRAPH_ENTITY_NOT_FOUND',
  GRAPH_QUERY_TOO_LARGE: 'GRAPH_QUERY_TOO_LARGE',
  GRAPH_NEO4J_UNAVAILABLE: 'GRAPH_NEO4J_UNAVAILABLE',

  // Ingestion (INGEST_*)
  INGEST_PAYLOAD_TOO_LARGE: 'INGEST_PAYLOAD_TOO_LARGE',
  INGEST_FORMAT_UNSUPPORTED: 'INGEST_FORMAT_UNSUPPORTED',
  INGEST_MAPPING_FAILED: 'INGEST_MAPPING_FAILED',

  // AI (AI_*)
  AI_NEURON_BUDGET_EXCEEDED: 'AI_NEURON_BUDGET_EXCEEDED',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_AGENT_INACTIVE: 'AI_AGENT_INACTIVE',

  // Cleanup (CLEANUP_*)
  CLEANUP_TASK_NOT_FOUND: 'CLEANUP_TASK_NOT_FOUND',
  CLEANUP_ALREADY_RUNNING: 'CLEANUP_ALREADY_RUNNING',

  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL: 'INTERNAL',
} as const;

/** Map error code to default HTTP status. */
export const STATUS_BY_CODE: Record<string, number> = {
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: 401,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: 401,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: 401,
  [ERROR_CODES.AUTH_TOKEN_REVOKED]: 401,
  [ERROR_CODES.AUTH_FORBIDDEN]: 403,
  [ERROR_CODES.AUTH_RATE_LIMITED]: 429,
  [ERROR_CODES.USER_NOT_FOUND]: 404,
  [ERROR_CODES.GRAPH_ENTITY_NOT_FOUND]: 404,
  [ERROR_CODES.GRAPH_ONTOLOGY_NOT_FOUND]: 404,
  [ERROR_CODES.CLEANUP_TASK_NOT_FOUND]: 404,
  [ERROR_CODES.USER_ALREADY_EXISTS]: 409,
  [ERROR_CODES.CLEANUP_ALREADY_RUNNING]: 409,
  [ERROR_CODES.USER_MAX_EXCEEDED]: 409,
  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.INGEST_PAYLOAD_TOO_LARGE]: 413,
  [ERROR_CODES.INGEST_FORMAT_UNSUPPORTED]: 415,
  [ERROR_CODES.AI_NEURON_BUDGET_EXCEEDED]: 429,
  [ERROR_CODES.AI_PROVIDER_UNAVAILABLE]: 503,
  [ERROR_CODES.GRAPH_NEO4J_UNAVAILABLE]: 503,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.INTERNAL]: 500,
};
