/**
 * HTTP header names used for cross-cutting concerns (auth, tracing).
 *
 * Cloudflare Workers are case-insensitive for header reads, but using the
 * same lowercase spelling everywhere keeps logs consistent.
 */
export const HEADERS = {
  /** Authorization header carrying `Bearer <jwt>`. */
  AUTHORIZATION: 'authorization',

  /** Tenant id injected by the Gateway before forwarding downstream. */
  TENANT_ID: 'x-tenant-id',

  /** User id injected by the Gateway. */
  USER_ID: 'x-user-id',

  /** User role injected by the Gateway. */
  USER_ROLE: 'x-user-role',

  /** Trace id propagated end-to-end (generated by the Gateway). */
  TRACE_ID: 'x-trace-id',

  /** Internal call marker; downstream services trust this only when the
   * request originates from another Worker in the same account. */
  INTERNAL: 'x-internal-call',

  /** Request id assigned by Cloudflare's edge (`cf-ray`). */
  CF_RAY: 'cf-ray',
} as const;
