/**
 * @fileoverview Recommendation center (建议中心): recommendations generated by
 * the LLM or the rule-based fallback, filtered by status (synced to
 * `?status=`), shown as cards.
 */

import type {RecStatus} from '@ontodecide/decision/contract';
import {useNavigate, useSearch} from '@tanstack/react-router';
import {Inbox} from 'lucide-react';
import {useTranslation} from 'react-i18next';
import {useRecommendations} from '../../features/decision/api';
import {RecommendationCard} from '../../features/decision/components/recommendation_card';
import {
  REC_FILTERS,
  type RecFilterTab,
  toRecFilter,
} from '../../features/decision/model';
import {errorMessage} from '../../shared/api/error_message';
import {EmptyState, ErrorView} from '../../shared/ui/empty_state';
import {PageHeader} from '../../shared/ui/page_header';
import {Skeleton} from '../../shared/ui/skeleton';
import {Tabs, TabsList, TabsTrigger} from '../../shared/ui/tabs';

/** Recommendation list page. */
export function RecommendationListPage() {
  const {t} = useTranslation('recommendations');
  const search = useSearch({strict: false}) as {status?: string};
  const navigate = useNavigate();
  const tab = toRecFilter(search.status);
  const q = useRecommendations(tab === 'All' ? {} : {status: tab as RecStatus});
  const items = [...(q.data ?? [])].sort((a, b) =>
    b.createdAt.localeCompare(a.createdAt),
  );

  const setTab = (v: string) => {
    const next = v as RecFilterTab;
    void navigate({
      to: '/recommendations',
      search: {status: next === 'Proposed' ? undefined : next},
      replace: true,
    });
  };

  return (
    <div className="flex flex-col gap-4">
      <PageHeader title={t('list.title')} description={t('list.description')} />

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList aria-label={t('list.filterAria')} className="flex-wrap">
          {REC_FILTERS.map(s => (
            <TabsTrigger key={s} value={s}>
              {s === 'All' ? t('list.all') : t(`common:recStatus.${s}`)}
            </TabsTrigger>
          ))}
        </TabsList>
      </Tabs>

      <section aria-live="polite" aria-busy={q.isLoading || undefined}>
        {q.isLoading ? (
          <div className="grid grid-cols-1 gap-3.5 md:grid-cols-2 xl:grid-cols-3">
            {[0, 1, 2].map(i => (
              <Skeleton key={i} className="h-48 rounded-[14px]" />
            ))}
          </div>
        ) : q.error ? (
          <ErrorView
            detail={errorMessage(q.error, t)}
            onRetry={() => void q.refetch()}
            className="glass"
          />
        ) : items.length === 0 ? (
          <div className="glass">
            <EmptyState
              icon={<Inbox aria-hidden />}
              title={t(`list.empty.${tab}`)}
              description={t(
                `list.emptyHint.${tab === 'Proposed' ? 'Proposed' : 'other'}`,
              )}
            />
          </div>
        ) : (
          <>
            <p className="mb-2 text-xs text-muted">
              {t('common:state.total', {count: items.length})}
            </p>
            <div className="grid grid-cols-1 gap-3.5 md:grid-cols-2 xl:grid-cols-3">
              {items.map(r => (
                <RecommendationCard key={r.id} rec={r} />
              ))}
            </div>
          </>
        )}
      </section>
    </div>
  );
}
